# Generated by Django 4.2.7 on 2026-04-18 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: 2023-2024', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('specialite', models.CharField(blank=True, max_length=150, null=True)),
                ('dernier_diplome', models.CharField(blank=True, max_length=100, null=True)),
                ('grade_academique', models.CharField(blank=True, max_length=100, null=True)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('National', 'National'), ('Etranger', 'Étranger')], max_length=20)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='management.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='faculties/logos/')),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=5, unique=True)),
                ('type', models.CharField(choices=[('Impair', 'Impair'), ('Pair', 'Pair')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='management.faculte')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite', models.PositiveIntegerField(blank=True, null=True)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='management.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='management.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='management.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='management.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='management.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='management.matiere')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='management.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=15)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='management.enseignement')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horaires', to='management.salle')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='management.faculte'),
        ),
        migrations.AddField(
            model_name='classe',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='management.departement'),
        ),
    ]
