# Generated by Django 6.0.4 on 2026-04-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Université Gamal Abdel Nasser de Conakry', max_length=200)),
                ('sigle', models.CharField(default='UGANC', max_length=20)),
                ('slogan', models.CharField(default='Le temple du savoir', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university/logos/')),
            ],
            options={
                'verbose_name': 'Université',
                'verbose_name_plural': 'Université',
            },
        ),
    ]
