# Generated by Django 6.0.4 on 2026-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_universite'),
    ]

    operations = [
        migrations.AddField(
            model_name='universite',
            name='bp',
            field=models.CharField(default='BP: 1147 Conakry', max_length=50),
        ),
        migrations.AddField(
            model_name='universite',
            name='email_contact',
            field=models.EmailField(default='info@uganc.edu.gn', max_length=100),
        ),
        migrations.AddField(
            model_name='universite',
            name='republique',
            field=models.CharField(default='RÉPUBLIQUE DE GUINÉE', max_length=100),
        ),
    ]
