# Generated by Django 6.0.4 on 2026-04-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_universite_bp_universite_email_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/photos/'),
        ),
    ]
