# Generated by Django 6.0.4 on 2026-04-21 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_enseignant_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('target_name', models.CharField(blank=True, max_length=150, null=True)),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('info', 'Information')], default='info', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('faculte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.faculte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité Récente',
                'verbose_name_plural': 'Activités Récentes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
