# Generated by Django 6.0.4 on 2026-04-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentactivity',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
