# Generated by Django 6.0.4 on 2026-05-09 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_recentactivity_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universite',
            options={'verbose_name': 'Université', 'verbose_name_plural': 'Universités'},
        ),
        migrations.AddField(
            model_name='faculte',
            name='universite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facultes', to='management.universite'),
        ),
        migrations.AlterField(
            model_name='universite',
            name='bp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='universite',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universite',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='universite',
            name='republique',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universite',
            name='sigle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='universite',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
