# Generated by Django 6.0.4 on 2026-05-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_universite_options_faculte_universite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universite',
            options={'verbose_name': 'Université', 'verbose_name_plural': 'Université'},
        ),
        migrations.AlterField(
            model_name='universite',
            name='bp',
            field=models.CharField(default='BP: 1147 Conakry', max_length=50),
        ),
        migrations.AlterField(
            model_name='universite',
            name='email_contact',
            field=models.EmailField(default='info@uganc.edu.gn', max_length=100),
        ),
        migrations.AlterField(
            model_name='universite',
            name='nom',
            field=models.CharField(default='Université Gamal Abdel Nasser de Conakry', max_length=200),
        ),
        migrations.AlterField(
            model_name='universite',
            name='republique',
            field=models.CharField(default='RÉPUBLIQUE DE GUINÉE', max_length=100),
        ),
        migrations.AlterField(
            model_name='universite',
            name='sigle',
            field=models.CharField(default='UGANC', max_length=20),
        ),
        migrations.AlterField(
            model_name='universite',
            name='slogan',
            field=models.CharField(default='Le temple du savoir', max_length=200),
        ),
    ]
