# Generated by Django 6.0.4 on 2026-05-25 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_universite_options_alter_universite_bp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enseignant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='management.enseignant'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.salle'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterUniqueTogether(
            name='emploidutemps',
            unique_together={('jour', 'heure_debut', 'heure_fin', 'salle')},
        ),
        migrations.CreateModel(
            name='SeancePointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('REPORTE', 'Reporté'), ('ANNULE', 'Annulé')], default='PRESENT', max_length=10)),
                ('heures_effectuees', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('motif', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='management.emploidutemps')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('emploi_du_temps', 'date')},
            },
        ),
    ]
