# Generated by Django 6.0.4 on 2026-06-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_userprofile_enseignant_alter_emploidutemps_jour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='nom',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
